name: Continuius Integration
on:
  pull_request:
    branchs: [main]
  push:
    branchs: [main]
jobs:
  ci:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Setup environment variables
        run: |
          touch .env
          echo POSTGRES_URL=${{ secrets.POSTGRE_URL }}
      - name: Run tests
        run: |
          npm install
          npx prisma db push
          npm run test:unit
